// Pet species and breed constants
export const SPECIES_LIST = [
  'Dog',
  'Cat', 
  'Bird',
  'Rabbit',
  'Hamster',
  'Guinea Pig',
  'Fish',
  'Reptile',
  'Others'
];

// Predefined breeds for each species
export const BREED_DATA: Record<string, string[]> = {
  Dog: [
    'Labrador Retriever',
    'Golden Retriever',
    'German Shepherd',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'German Shorthaired Pointer',
    'Yorkshire Terrier',
    'Siberian Husky',
    'Dachshund',
    'Pembroke Welsh Corgi',
    'Australian Shepherd',
    'Boston Terrier',
    'Shih Tzu',
    'Chihuahua',
    'Border Collie',
    'Great Dane',
    'Boxer',
    'Mixed Breed'
  ],
  Cat: [
    'Persian',
    'Maine Coon',
    'British Shorthair',
    'Ragdoll',
    'Bengal',
    'Abyssinian',
    'Birman',
    'Oriental Shorthair',
    'American Shorthair',
    'Scottish Fold',
    'Sphynx',
    'Devon Rex',
    'Russian Blue',
    'Siamese',
    'Norwegian Forest Cat',
    'Exotic Shorthair',
    'Turkish Angora',
    'Munchkin',
    'Bombay',
    'Mixed Breed'
  ],
  Bird: [
    'Canary',
    'Budgerigar',
    'Cockatiel',
    'Lovebird',
    'Conure',
    'African Grey',
    'Macaw',
    'Amazon Parrot',
    'Cockatoo',
    'Finch',
    'Parakeet',
    'Pigeon',
    'Dove',
    'Mynah',
    'Cardinal',
    'Robin',
    'Sparrow',
    'Other'
  ],
  Rabbit: [
    'Holland Lop',
    'Netherland Dwarf',
    'Mini Rex',
    'Lionhead',
    'Flemish Giant',
    'New Zealand',
    'Californian',
    'English Angora',
    'Dutch',
    'Polish',
    'French Lop',
    'English Lop',
    'Jersey Wooly',
    'American Fuzzy Lop',
    'Rex',
    'Himalayan',
    'Mixed Breed'
  ],
  Hamster: [
    'Syrian Hamster',
    'Dwarf Campbell Russian',
    'Dwarf Winter White Russian',
    'Chinese Hamster',
    'Roborovski Dwarf',
    'European Hamster',
    'Other'
  ],
  'Guinea Pig': [
    'American',
    'Abyssinian',
    'Peruvian',
    'Silkie',
    'Teddy',
    'Rex',
    'Coronet',
    'Texel',
    'Alpaca',
    'Lunkarya',
    'Mixed Breed'
  ],
  Fish: [
    'Goldfish',
    'Betta',
    'Angelfish',
    'Guppy',
    'Tetra',
    'Molly',
    'Platy',
    'Swordtail',
    'Barb',
    'Danio',
    'Catfish',
    'Cichlid',
    'Discus',
    'Koi',
    'Other'
  ],
  Reptile: [
    'Bearded Dragon',
    'Leopard Gecko',
    'Ball Python',
    'Corn Snake',
    'Red-Eared Slider',
    'Russian Tortoise',
    'Blue Tongue Skink',
    'Crested Gecko',
    'Green Iguana',
    'Chinese Water Dragon',
    'Chameleon',
    'Monitor Lizard',
    'Axolotl',
    'Other'
  ]
};

// Local storage key for custom species
export const CUSTOM_SPECIES_KEY = 'zambovet_custom_species';